"""initial process and module tables

Revision ID: 01b7686b1c41
Revises: 
Create Date: 2026-04-16 23:57:28.425227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01b7686b1c41'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('module_id', sa.String(length=100), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('module_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_module_configs_module_id'), ['module_id'], unique=False)

    op.create_table('process_definitions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('graph', sa.JSON(), nullable=False),
    sa.Column('node_count', sa.Integer(), nullable=False),
    sa.Column('edge_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('process_instances',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('definition_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['definition_id'], ['process_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('process_instances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_process_instances_definition_id'), ['definition_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('process_instances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_process_instances_definition_id'))

    op.drop_table('process_instances')
    op.drop_table('process_definitions')
    with op.batch_alter_table('module_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_module_configs_module_id'))

    op.drop_table('module_configs')
    # ### end Alembic commands ###
